# Generated by Django 4.1 on 2022-08-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('sku', models.CharField(default='', max_length=500)),
                ('price', models.IntegerField(default=0, max_length=500)),
                ('image', models.URLField(default='')),
            ],
        ),
    ]
